In [7]:
import numpy as np

def forward_pass_with_dropout(X, W, b, dropout_rate=0.5):
    """
    Performs a forward pass through a neural network layer with dropout.
    
    :param X: Input data, numpy array of shape (n_samples, n_features)
    :param W: Weights, numpy array of shape (n_features, n_units)
    :param b: Biases, numpy array of shape (n_units,)
    :param dropout_rate: The fraction of neurons to drop out during training
    :return: Activations after the layer, with dropout applied
    """
    # Compute the linear part of the forward pass
    Z = np.dot(X, W) + b
    
    # Apply a ReLU activation function (just as an example)
    A = np.maximum(0, Z)
    
    # Apply dropout
    # Create a mask indicating which neurons to keep
    keep_prob = 1 - dropout_rate
    mask = np.random.rand(*A.shape) < keep_prob
    
    # Apply the mask to the activations
    A_dropout = A * mask
    
    # Scale the activations by the keep probability to maintain expected value
    A_dropout /= keep_prob
    
    return A_dropout

# Example usage
np.random.seed(0)
X = np.random.randn(10, 5)  # 10 samples, 5 features
W = np.random.randn(5, 3)   # 5 input features, 3 output neurons
b = np.random.randn(3)      # 3 output neurons

# Apply forward pass with dropout
A_dropout = forward_pass_with_dropout(X, W, b, dropout_rate=0.5)
print(A_dropout)


[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         1.12875402]
 [0.         0.         1.59666881]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [3.61396188 0.         0.        ]
 [4.55944626 0.         0.39859551]]
